// Players = {
//   id: number,
//   //등번호
//   name: string,
//   already: boolean,
//   //들어가있는지 유무

//   //주장 유무랑 포지션 추가 예정
// }

export const info = [
  {
    name: "이성훈",
    gender: "남",
    email: "성훈@naver.com",
    nickName: "닉성훈",
    region: "성훈서울",
    like: "성훈ST",
    player: false,
    info: "안녕하세요 저는 이성훈 입니다."
  },
  {
    name: "최부기",
    gender: "남",
    email: "부기@naver.com",
    nickName: "닉부기",
    region: "부기서울",
    like: "부기ST",
    player: false,
    info: "안녕하세요 저는 최부기입니다",
  },
  {
    name: "윤성록",
    gender: "남",
    email: "성록@naver.com",
    nickName: "닉성록",
    region: "성록서울",
    like: "성록ST",
    player: false,
    info: "안녕하세요 저는 윤성록입니다",
  },
  {
    name: "정지원",
    gender: "남",
    email: "지원@naver.com",
    nickName: "닉지원",
    region: "지원서울",
    like: "지원ST",
    player: false,
    info: "안녕하세요 저는 정지원입니다",
  },
  {
    name: "이재이",
    gender: "여",
    email: "재이@naver.com",
    nickName: "닉재이",
    region: "재이서울",
    like: "재이ST",
    player: false,
    info: "안녕하세요 저는 이재이입니다",
  },
  {
    name: "김동기",
    gender: "남",
    email: "동기@naver.com",
    nickName: "닉동기",
    region: "동기서울",
    like: "동기ST",
    player: false,
    info: "안녕하세요 저는 김동기입니다",
  },
  {
    name: "이진성",
    gender: "남",
    email: "진성@naver.com",
    nickName: "닉진성",
    region: "진성서울",
    like: "진성ST",
    player: false,
    info: "안녕하세요 저는 이진성입니다",
  },
  {
    name: "차준혁",
    gender: "남",
    email: "준혁@naver.com",
    nickName: "닉준혁",
    region: "준혁서울",
    like: "준혁ST",
    player: false,
    info: "안녕하세요 저는 차준혁입니다",
  },
  {
    name: "강승우",
    gender: "남",
    email: "승우@naver.com",
    nickName: "닉승우",
    region: "승우서울",
    like: "승우ST",
    player: false,
    info: "안녕하세요 저는 강승우입니다",
  },
  {
    name: "박길우",
    gender: "남",
    email: "박길우@naver.com",
    nickName: "닉길우",
    region: "길우서울",
    like: "길우ST",
    player: false,
    info: "안녕하세요 저는 박길우입니다",
  },
  {
    name: "박승태",
    gender: "남",
    email: "승태@naver.com",
    nickName: "닉승태",
    region: "승태서울",
    like: "승태ST",
    player: false,
    info: "안녕하세요 저는 박승태입니다",
  },
  {
    name: "신승우",
    gender: "남",
    email: "신승우@naver.com",
    nickName: "닉승우",
    region: "신승우서울",
    like: "신승우ST",
    player: false,
    info: "안녕하세요 저는 신승우입니다",
  },
  {
    name: "이지현",
    gender: "여",
    email: "지현@naver.com",
    nickName: "닉지현",
    region: "지현서울",
    like: "지현ST",
    player: false,
    info: "안녕하세요 저는 이지현입니다",
  },
  {
    name: "이찬근",
    gender: "남",
    email: "찬근@naver.com",
    nickName: "닉찬근",
    region: "찬근서울",
    like: "ST",
    player: false,
    info: "안녕하세요 저는 이찬근입니다",
  },
];